name: Release new libraries versions

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (no v prefix)'
        required: true
        default: '0.0.0'

      publish_lib:
        description: 'Publish lib to npm'
        required: true
        type: boolean
        default: true

      publish_cli:
        description: 'Publish CLI to npm'
        required: true
        type: boolean
        default: true

permissions:
  contents: read
  packages: write

jobs:
  publish-crypto:
    name: Publish @senclosed/crypto to npm
    if: ${{ github.event.inputs.publish_lib || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: packages/crypto

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Publish @senclosed/crypto to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  publish-lib:
    name: Publish @senclosed/lib to npm
    if: ${{ github.event.inputs.publish_lib || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: packages/lib

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Publish  @senclosed/lib to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-cli:
    name: Publish @senclosed/cli to npm
    if: ${{ github.event.inputs.publish_cli || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: packages/cli

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm i
        working-directory: ./

      - name: Publish @senclosed/lib to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}